In [3]:
import pandas as pd

In [4]:
movies = pd.read_csv(r'C:\Users\adars\Full_stack_data _Science_with_Ai\Full_stack_data _Science_with_Ai\practice_Projects_&_Task\MovieLens_20M_Dataset_project\archive_dataset\movie.csv')

In [5]:
movies.shape

(27278, 3)

In [6]:
rating = pd.read_csv(r'C:\Users\adars\Full_stack_data _Science_with_Ai\Full_stack_data _Science_with_Ai\practice_Projects_&_Task\MovieLens_20M_Dataset_project\archive_dataset\rating.csv')

In [7]:
rating.shape

(20000263, 4)

In [8]:
tag = pd.read_csv(r'C:\Users\adars\Full_stack_data _Science_with_Ai\Full_stack_data _Science_with_Ai\practice_Projects_&_Task\MovieLens_20M_Dataset_project\archive_dataset\tag.csv')

In [9]:
tag.shape

(465564, 4)

In [11]:
print(movies.columns)
print(rating.columns)
print(tag.columns)

Index(['movieId', 'title', 'genres'], dtype='str')
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')
Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='str')

In [18]:
row_0 = tag.iloc[1]
type(row_0)

pandas.Series

In [19]:
print(row_0)

userId                        65
movieId                      208
tag                    dark hero
timestamp    2013-05-10 01:41:18
Name: 1, dtype: object

In [20]:
row_0['userId']

np.int64(65)

In [21]:
row_0['userId']

np.int64(65)

In [22]:
row_0.name

1

In [23]:
row_0 = row_0.rename('firstRow')
row_0.name

'firstRow'

In [25]:
tag.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [27]:
tag.index

RangeIndex(start=0, stop=465564, step=1)

In [30]:
tag.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='str')

In [32]:
tag.iloc[ [0,11,500] ]

     userId  movieId                tag            timestamp
0        18     4141        Mark Waters  2009-04-24 18:19:40
11       65     1783      noir thriller  2013-05-10 01:39:43
500     342    55908  entirely dialogue  2012-01-31 18:41:16