In [1]:
import pandas as pd

In [27]:
emp = pd.read_excel(r"C:\Users\adars\Full_stack_data _Science_with_Ai\Full_stack_data _Science_with_Ai\Python\29_EDA_\rawdata.xlsx")

In [28]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [29]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [30]:
emp .info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       4 non-null      str
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       5 non-null      str
dtypes: str(6)
memory usage: 619.0 bytes

In [31]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [32]:
emp.dtypes

Name        str
Domain      str
Age         str
Location    str
Salary      str
Exp         str
dtype: object

DATA CLEANING

In [33]:
emp["Name"]

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: str

In [36]:
emp["Name"]=emp["Name"].str.replace(r"\W","",regex=True)

In [37]:
emp["Name"]

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: str

In [39]:
emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [42]:
emp["Age"]=emp["Age"].str.extract(r"\d+","")

TypeError: unsupported operand type(s) for &: 'str' and 'int'

In [ ]:
emp["Age"]

In [ ]:
emp

In [22]:
emp["Salary"]=emp["Salary"].str.replace(r"\W","",regex=True)

In [23]:
emp

    Name          Domain       Age   Location Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5000       2+
1  Teddy         Testing    45' yr  Bangalore  10000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  15000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad  20000      NaN
4  Uttam      Statistics     67-yr        NaN  30000  5+ year
5    Kim             NLP      55yr      Delhi  60000      10+

In [24]:
emp["Domian"]=emp["Domain"].str.replace(r"\W","",regex=True)

In [25]:
emp

    Name          Domain       Age   Location Salary      Exp       Domian
0   Mike   Datascience#$  34 years     Mumbai   5000       2+  Datascience
1  Teddy         Testing    45' yr  Bangalore  10000       <3      Testing
2   Umar  Dataanalyst^^#       NaN        NaN  15000   4> yrs  Dataanalyst
3   Jane     Ana^^lytics       NaN   Hyderbad  20000      NaN    Analytics
4  Uttam      Statistics     67-yr        NaN  30000  5+ year   Statistics
5    Kim             NLP      55yr      Delhi  60000      10+          NLP

In [ ]:
emp.head()

In [12]:
emp["Exp"]=emp["Exp"].str.extract(r"\d+","")

TypeError: unsupported operand type(s) for &: 'str' and 'int'

In [13]:
emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [14]:
clean_data=emp.copy()

In [15]:
clean_data

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [16]:
import numpy as np

In [17]:
clean_data["Age"]=clean_data["Age"].fillna(np.mean(pd.to_numeric(clean_data["Age"])))

ValueError: Unable to parse string "34 years" at position 0

In [18]:
clean_data

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [19]:
clean_data["Exp"]=clean_data["Exp"].fillna(np.mean(pd.to_numeric(clean_data["Exp"])))

ValueError: Unable to parse string "2+" at position 0

In [20]:
clean_data["Exp"]=clean_data["Exp"].fillna(np.mode(pd.to_numeric(clean_data["Exp"])))

AttributeError: module 'numpy' has no attribute 'mode'

In [21]:
clean_data["Age"]=clean_data["Age"].astype(int)

ValueError: cannot convert float NaN to integer

In [ ]:
clean_data